- api/giffygram.json
1. Added file `giffygram.json` to `api` directory.
1. Modified file `giffygram.json` to include `basic database objects and dummy data`.
​
```
git checkout al-branch-postwall
```
2. Open a new Terminal tab and navigate to the server directory.
> Open up JSON server database in web browser
> Look at the new objects created and their contents
> add dummy objects to json database

- src/scripts/data/provider.js
1. Modified file `providers.js` to include app state and functionality.
​
```
git checkout al-branch-dataprovider
```
> Check out the appState object
> fetchPosts function defined

- api/giffygram.json
- src/scripts/GiffyGram.js
- src/scripts/data/provider.js
- src/scripts/main.js
1. Added some outline HTML to giffygram.js and created NavBar.js module
1. Modified file `provider.js` to include `fetch call to get likes` and functionality.
​
```
git checkout slm-giffygram-looksmart
```
> Not applicable at this moment
> Issue # 18 and Issue #13 completed

- src/scripts/data/provider.js
Fetch call for messages not posts!!!
​
```
```
> Implemented a fetch call for messages

- src/scripts/data/provider.js
- src/scripts/main.js
1. Modified file `provider.js` to include `setter function for new user` and functionality.
​
```
git checkout al-branch-registerform
```
> Inspect provider.js and main.js for new dispatch event and event listener
> added setter functions for new user, added dispatch and event listener

- src/scripts/data/provider.js
- src/scripts/nav/Footer.js
> Added html to the footer.js

- src/scripts/data/provider.js
- src/scripts/feed/PostEntry.js
- src/scripts/feed/PostList.js
- src/scripts/main.js
1. Added file `PostEntry.js` to `feed` directory.
1. Modified file `provider.js` to include `sendGif()` a setter function for new user posts
​
```
git checkout slm-giffygram-looksmart
```
> Not applicable yet
> Setter Function for New Gif Posts, Completed PostEntry.js

- src/scripts/auth/Register.js
> we made a few more changes while looking through it

- src/scripts/main.js
> mainJS restored

- api/giffygram.json
- src/scripts/auth/Register.js
- src/scripts/data/provider.js
- src/scripts/main.js
1. Modified file `main.js` to include `render`
2. Changed `register.js` to break out of infinite registration loop
​
```
git checkout al-branch-tryingtorender
```
> Serve API and index.html
> Check login functionality and registration functionality
> giffygram now rendering

- src/scripts/GiffyGram.js
- src/scripts/nav/Footer.js
> Footer is visible in dom but no event yet

- api/giffygram.json
- src/scripts/GiffyGram.js
- src/scripts/auth/Register.js
- src/scripts/nav/NavBar.js
1. Added to file `NavBar.js' to allow users to log out
1. Modified file `register.js` to refresh to log-in page
​
```
git checkout al-branch-testx
```
> Test this code by creating new user, logging in and logging out
> Al branch testx

- api/giffygram.json
- src/scripts/auth/Login.js
- src/scripts/auth/Register.js
1. Modified files `register.js` and `login.js` to include `checks for blank entries, repeats in database`
2. Fixed the faulty check against users in the database by refactoring authentication function
​
```
git checkout al-branch-fixregister
```
> Test to see whether you can re-register with account already in database
> login, logout, register all working

- src/index.html
- src/scripts/feed/PostList.js
- src/scripts/nav/Footer.js
1. Added file `filename` to `directoryname` directory. footer.js
1. Modified file `filename` to include eventListeners for all events in the footer 
​
```
```
> Working on eventListeners for footer.

- src/scripts/GiffyGram.js
- src/scripts/feed/PostList.js
1. Modified file `PostList.js` to include functionality to display HTML 
​
```
git checkout slm-giffygram-2
```
> Pull and serve this branch. Note that the title, gif description, time and user are displaying; as well as the star.
> PostList is diplaying all needed info

- src/scripts/GiffyGram.js
- src/scripts/auth/Register.js
- src/scripts/feed/Post.js
- src/scripts/nav/Footer.js
- src/scripts/nav/NavBar.js
- src/styles/post.css
1. Modified file `Post.js` to include `innerHTML functionality`.
​
```
git checkout al-branch-innerhtmlchain
```
> Test what happens when you hit the Post button. It should rerender the html of ".postEntry" at the top of the site;
> got posting component to render properly

- api/giffygram.json
- src/scripts/data/provider.js
- src/scripts/feed/PostEntry.js
- src/scripts/feed/PostList.js
1. Modified file `PostList.js` to include different star colors based on user information
2. 
```
git checkout slm-giffygram-3
```
> Serve to localhost. check that favorite stars are both yellow and blank depending on user data.
> PostList.js - got stars to change based on user information

- src/scripts/data/provider.js
- src/scripts/feed/PostEntry.js
- src/scripts/nav/Footer.js
> Mrw footer 4

- api/giffygram.json
- src/scripts/GiffyGram.js
- src/scripts/data/provider.js
- src/scripts/friends/DirectMessage.js
- src/scripts/main.js
- src/scripts/message/MessageForm.js
- src/scripts/nav/NavBar.js
- src/styles/main.css
- src/styles/message.css
- src/styles/navigation.css
1. Modified file `DirectMessages.js` to include `dm component` and delete message functionality.
​
```
git checkout al-branch-dmbox
```
> Send a message to your own account; test to see whether it appears in DM's component; delete it
> Al branch dmbox

- api/giffygram.json
- src/scripts/GiffyGram.js
- src/scripts/data/provider.js
- src/scripts/feed/PostList.js
- src/scripts/nav/FilterByUser.js
- src/scripts/nav/FilterByYear.js
- src/scripts/nav/Footer.js
1. Added file `FilterByUser.js` to `nav` directory.
1. Modified file `Footer.js` to include `filter by user name option` and functionality.
​
```
git checkout al-branch-footerx
```
> See whether the dropdown in the footer allows for filtering of wall by user
> Al branch footerx

- api/giffygram.json
- src/scripts/GiffyGram.js
- src/scripts/data/provider.js
- src/scripts/feed/PostEntry.js
- src/scripts/feed/PostList.js
1. Modified file `postEntry.js` to include ability of users to post new gifs
2. 
```
git checkout slm-giffygram-4
```
> On the homepage, click GiffyPost, then enter the fields with necessary items. Click save.
> Example: When user clicks save, then HTML should render with new post.
> Slm giffygram 4

- api/giffygram.json
- src/scripts/GiffyGram.js
- src/scripts/data/provider.js
- src/scripts/friends/DirectMessage.js
- src/scripts/message/MessageForm.js
- src/scripts/nav/NavBar.js
- src/styles/main.css
- src/styles/message.css
> Al branch dmbox mark as read

- api/giffygram.json
- src/scripts/data/provider.js
- src/scripts/friends/DirectMessage.js
- src/scripts/main.js
- src/scripts/message/MessageForm.js
- src/scripts/nav/NavBar.js
- src/styles/message.css
- src/styles/navigation.css
1. Modified files `MessageForm.js, NavBar.js, and Main.js`` to include `check for blank input in DM form, message counter, and second CustomEvent to prevent DM box from closing upon deleting message or marking it as read`.
​
```
git checkout al-branch-dmbox2
```
> Test that the DM component to see whether it registers new messages and whether the DM box goes away when you mark as read/delete message
> Al branch dmbox2

- api/giffygram.json
- src/scripts/main.js
- src/scripts/nav/Footer.js
1. Modified file `Footer.js` to include uncheck/refresh functionality to `Show Only Favorites` component.
​
```
git checkout al-branch-showNonFavorites
```
> Check to see whether the checkbox in the footer does only show favorited posts upon click; then check whether it shows all posts upon another click
> got favorites list to unfilter

- api/giffygram.json
- src/scripts/feed/PostEntry.js
> Al branch edit post entry

- api/giffygram.json
- src/scripts/feed/PostList.js
> unfavorite now works

- api/giffygram.json
- src/scripts/data/provider.js
- src/scripts/feed/PostList.js
- src/styles/feed.css
1. Modified file `PostList.js` to include
​
```
git checkout slm-giffygram-5
```
DELETE FUNCTIONALITY
> Slm giffygram 5

- api/giffygram.json
- src/scripts/nav/FilterByLikes.js
- src/scripts/nav/Footer.js
> Mrw styling

- api/giffygram.json
- src/scripts/feed/PostList.js
1. Modified file `PostList.js` to update position of DeleteIcon and include parameter
​
```
git checkout slm-giffygram-6
```
> Slm giffygram 6
